apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce

  volumeName: minio-pv

  resources:
    requests:
      storage: 20Gi